// summarize-tiles.ts — describe cache/berlin.mbtiles and write the result to tiles-summary.txt.
//
// Reports: sqlite schema (planetiler's default "compact" layout makes `tiles` a view over tiles_shallow/tiles_data),
// tile counts and sizes per zoom, the compression of every tile blob (from the first two bytes), one decoded tile's
// layers as a sanity check, and the metadata table with the vector_layers pulled out of its `json` row.
// Run: bun run corpus/summarize-tiles.ts [path/to.mbtiles]
import { Database } from "bun:sqlite";
import { statSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { VectorTile } from "@mapbox/vector-tile";
import Pbf from "pbf";

const here = dirname(new URL(import.meta.url).pathname);
const path = Bun.argv[2] ?? join(here, "cache", "berlin.mbtiles");
const db = new Database(path, { readonly: true });
const lines: string[] = [];
const out = (s = "") => lines.push(s);

out(`# tiles-summary.txt — generated by summarize-tiles.ts from cache/${basename(path)}`);
out(`file_size_bytes\t${statSync(path).size}`);
out();

out("## sqlite schema");
for (const r of db.query<{ type: string; name: string }, []>("select type, name from sqlite_master where type in ('table','view','index') order by type desc, name").all()) {
  out(`${r.type}\t${r.name}`);
}
out();

out("## tiles");
const total = db.query<{ n: number }, []>("select count(*) as n from tiles").get()!.n;
const distinct = db.query<{ n: number }, []>("select count(*) as n from tiles_data").get()?.n;
out(`total_tiles\t${total}`);
if (distinct !== undefined) out(`distinct_blobs\t${distinct}\t(compact mode: identical tiles share one blob)`);
out("zoom\ttiles\tmin_bytes\tmax_bytes\tavg_bytes\tsum_bytes");
for (const r of db
  .query<{ z: number; n: number; mn: number; mx: number; av: number; tot: number }, []>(
    "select zoom_level z, count(*) n, min(length(tile_data)) mn, max(length(tile_data)) mx, round(avg(length(tile_data))) av, sum(length(tile_data)) tot from tiles group by zoom_level order by zoom_level",
  )
  .all()) {
  out(`${r.z}\t${r.n}\t${r.mn}\t${r.mx}\t${r.av}\t${r.tot}`);
}
out();

out("## tile blob compression (first two bytes of every blob)");
for (const r of db.query<{ magic: string; n: number }, []>("select hex(substr(tile_data,1,2)) magic, count(*) n from tiles group by magic order by n desc").all()) {
  const label = r.magic === "1F8B" ? "gzip" : r.magic === "1A" || r.magic.startsWith("1A") ? "raw MVT" : "unknown";
  out(`${r.magic}\t${r.n}\t${label}`);
}
out();

out("## decoded sample tile");
const sample = db
  .query<{ z: number; x: number; y: number; d: Uint8Array }, []>("select zoom_level z, tile_column x, tile_row y, tile_data d from tiles where zoom_level = 14 order by length(tile_data) desc limit 1")
  .get()!;
const isGzip = sample.d[0] === 0x1f && sample.d[1] === 0x8b;
const raw = isGzip ? Bun.gunzipSync(sample.d as Uint8Array<ArrayBuffer>) : sample.d;
const tile = new VectorTile(new Pbf(raw));
out(`largest z14 tile\tz=${sample.z} x=${sample.x} tms_y=${sample.y} (xyz_y=${(1 << sample.z) - 1 - sample.y})\t${sample.d.length} bytes gzip -> ${raw.length} bytes MVT`);
for (const [name, layer] of Object.entries(tile.layers)) out(`layer\t${name}\t${layer.length} features\textent ${layer.extent}`);
out();

out("## metadata table");
const meta = db.query<{ name: string; value: string }, []>("select name, value from metadata order by name").all();
for (const r of meta) {
  if (r.name === "json") continue;
  out(`${r.name}\t${r.value}`);
}
const json = meta.find((r) => r.name === "json");
if (json) {
  const parsed = JSON.parse(json.value) as { vector_layers?: Array<{ id: string; minzoom?: number; maxzoom?: number; fields?: Record<string, string> }> };
  out();
  out("## metadata.json vector_layers");
  out("id\tminzoom\tmaxzoom\tfields");
  for (const l of parsed.vector_layers ?? []) out(`${l.id}\t${l.minzoom ?? ""}\t${l.maxzoom ?? ""}\t${Object.keys(l.fields ?? {}).join(",")}`);
}

const text = lines.join("\n") + "\n";
await Bun.write(join(here, "tiles-summary.txt"), text);
process.stdout.write(text);
